<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--Elemento raíz. torneoATP-->
    <xs:element name="torneoATP">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="torneo" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string">
                            <xs:element name="fechaIni" type="xs:date">
                            <xs:element name="fechaFin" type="xs:date">
                            <xs:element name="puntosATP" type ="typePuntosATP">
                            <xs:element name="cuadro" type="typeCuadro">
                            <xs:element name="partidos" type="typePartidos">
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Puntos ATP-->
        <!--Valores válidos para Ronda-->
         <xs:simpleType name="rondaValues">
            <xs:restriction base="xs:string">
                <xs:enumeration value="2da ronda"/>
                <xs:enumeration value="3ra ronda"/>
                <xs:enumeration value="cuartos"/>
                <xs:enumeration value="semis"/>
                <xs:enumeration value="finalista"/>
                <xs:enumeration value="ganador"/>
            </xs:restriction>
         </xs:simpleType>

    <xs:complexType name="typePuntosATP">
        <xs:sequence>
            <xs:element name="ronda" minOccurs="3" maxOccurs="6">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="rondaValues">
                            <xs:attribute name="puntos" type="xs:positiveInteger" use="requiered">
                        </xs:extendion> 
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <!--Cuadro--> 
    <xs:complexType name="typeCuadro">
        <xs:sequence>
            <xs:element name="cruce" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="jugador" minOccurs="2" maxOccurs="2">
                            <xs:complexType>
                                <xs:attribute name="nombre" type="xs:string" use="required"/>
                                <xs:attribute name="rankingTorneo" type="xs:positiveInteger" use="required"/>
                            </xs:complexType>
                        </xs:element>  
                       </xs:sequence>
                    <xs:attribute name="numero" type="xs:positiveInteger" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
   </xs:complexType>
   <!--Partido-->
                 

           

