<!ELEMENT torneosATP (torneo+)>

<!ELEMENT torneo (nombre, fechaIni, fechaFin, puntosATP, cuadro, partidos,resultado+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaIni (#PCDATA)>
<!ELEMENT fechaFin (#PCDATA)>

<!ELEMENT puntosATP (ronda,ronda,ronda,ronda?,ronda?,ronda?)>
<!ELEMENT ronda (#PCDATA)>
<!ATTLIST ronda puntos CDATA "" >

<!ELEMENT cuadro (cruce+)>
<!ELEMENT cruce (jugador,jugador)>
<!ATTLIST cruce numero CDATA #IMPLIED>
<!ELEMENT jugador EMPTY >
<!ATTLIST jugador nombre CDATA #REQUIRED>
<!ATTLIST jugador rankingTorneo CDATA #REQUIRED>

<!ELEMENT partidos (partido+)>
<!ELEMENT partido (tipo, jugadores+)> <!--Un partido solo puede ser de un tipo-->
<!ATTLIST partido estado CDATA #IMPLIED>
<!ELEMENT tipo (#PCDATA) >
<!ELEMENT jugadores (lado1,lado2)>
<!ELEMENT lado1 (jugador?)>
<!ELEMENT lado2 (jugador?)>

<!ELEMENT resultado (set+)>
<!ELEMENT set (juegos)>
<!ATTLIST set numero CDATA "0">
<!ELEMENT juegos (puntosJuego?)>
<!ATTLIST juegos lado1 CDATA "0">
<!ATTLIST juegos lado2 CDATA "0">
<!ELEMENT puntosJuego (#PCDATA)>
<!ATTLIST puntosJuego lado1 (0|10|30|40|AD) "0" >
<!ATTLIST puntosJuego lado2 (0|10|30|40|AD) "0" >


